# Generated by Django 5.1.2 on 2024-10-31 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_customfield_field_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='employee',
        ),
    ]
