# Generated by Django 5.1.2 on 2024-10-31 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_auths', '0003_alter_employeeprofile_position_delete_customfield_and_more'),
        ('admin_app', '0002_remove_customfield_field_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='admin_app.customfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
