# Generated by Django 5.1.2 on 2024-10-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_auths', '0004_customfieldvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvalue',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
